language: node_js
node_js:
- 8
script: npm run build
sudo: required
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
branches:
  only:
  - master
notifications:
  slack:
    secure: eo1JSnBOnCPHdn5NBfAeteyl0PK2yA6rs/7NLEYjNjBwEOmt/PbFq5IW6/o9uCLGzQu1BnLr3uChZQCnTNsvDcBRXO/ZJStB/sn7J1Fsv/FUL41XPGjzuGzKGVJyyMkJ4xIGqyoPnhg2aGeDL5D/7O6EwafwTersmxWDbBVvzEQdJn1OrdWHE9akLgk7kZurXgxpmvjl72DrFFo/O3UUaLvS1rs7rjpGVn3HPjZqfs5zJN6l+j1lFf03s3M9xDqaYT2Wy9hS1hj2I8HJP+JGleIG8AyRbPEsmtbU0L67SgHv0fsYhaW5Mf//YIaz8p3YZtcfziyZfWl+R10fZ1gmGIalL8KdfKYdlnEsT/8vQLMcHWbd12Vr8XFAA6UCJcrzcTSppp8afFw/hWp1AU2NGeIGyIUyhIIIXiYT2cKgkg2ddTpkTsVoq5SbDoKMkj26fT4Qf6ShF50MdBBC6CNyQhd5i+LFG8M+RmT7jHCxDYzTOfIB0VkHEjUbvZi0PQex6mky5xc7WErgPbVusHh8HR8ueODEw//pQJuvYHuAwecn8FmgWd3sxKPJUSO0JkP2S0lVU66nAhh5aqrxu1GFUVz9QmKsdPjKc1h65wP4xHsiT2Ekwp/hsXueggVxHM0D+eNwdTC/KZuMM/HAmLWLYQyotwf8HPQawUThWQEkUsI=
